services:
  ultrafeeder:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder
    tty: true
    container_name: ultrafeeder
    hostname: ultrafeeder
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 189:* rwm'
    ports:
      - 8080:80               # to expose the web interface
      - 9273-9274:9273-9274   # to expose the statistics interface to Prometheus
      - 30002:30002           # raw out
      - 30005:30005           # beast out
      - 30047:30047           # json out
    environment:
      # --------------------------------------------------
      # general parameters:
      - LOGLEVEL=error
      - TZ=America/Los_Angeles
      # --------------------------------------------------
      # SDR related parameters:
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_RTLSDR_DEVICE=stx:0:0
# warning: swag follows
      - READSB_RTLSDR_PPM=20
      #
      # --------------------------------------------------
      # readsb/decoder parameters:
      - READSB_LAT=44.88670038655793
      - READSB_LON=-123.03142117287913
      - READSB_ALT=131m
      - READSB_GAIN=autogain
      - READSB_MODEAC=true
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - ENABLE_TIMELAPSE1090=false
      #
      # --------------------------------------------------
      # Sources and Aggregator connections:
      # (Note - remove the ones you are not using / feeding)
      - READSB_NET_CONNECTOR=10.0.0.153,37981,raw_in;feed1.adsbexchange.com,30004,beast_reduce_plus_out,uuid=479dd048-9584-425d-a010-4f9a86a980d5
        #- READSB_NET_CONNECTOR=dump978,37981,raw_in
      - UUID=6f0153b5-44a9-4461-9595-c0327259c8c4
      #
      # --------------------------------------------------
      # MLAT and MLATHUB related parameters:
      # MLAT_CONFIG defines who you are feeding MLAT data to, and on what port(s) the results will become available
      - MLAT_CONFIG=
        #    feed.adsb.fi,31090,39000;
        #  in.adsb.lol,31090,39001;
        #  feed.adsb.one,64006,39002;
        #  mlat.planespotters.net,31090,39003;
        #  feed.theairtraffic.com,31090,39004
        # feed.adsbexchange.com,31090,39005
      - MLAT_USER=${FEEDER_NAME}
      # MLATHUB automatically gets MLAT results data from the feeders defined in MLAT_CONFIG,
      # and additionally from the Net Connectors defined with MLATHUB_NET_CONNECTOR
      - MLATHUB_NET_CONNECTOR=
        #   piaware,30105,beast_in;
        #  rbfeeder,30105,beast_in;
        #  radarvirtuel,30105,beast_in
      #
      # --------------------------------------------------
      # TAR1090 (Map Web Page) parameters:
      - UPDATE_TAR1090=true
      - TAR1090_DEFAULTCENTERLAT=${FEEDER_LAT}
      - TAR1090_DEFAULTCENTERLON=${FEEDER_LONG}
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_PAGETITLE=${FEEDER_NAME}
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_ENABLE_AC_DB=true
      - TAR1090_FLIGHTAWARELINKS=true
      - HEYWHATSTHAT_PANORAMA_ID=${FEEDER_HEYWHATSTHAT_ID}
      - HEYWHATSTHAT_ALTS=${FEEDER_HEYWHATSTHAT_ALTS}
      - TAR1090_SITESHOW=true
      - TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
      - TAR1090_RANGE_OUTLINE_WIDTH=2.0
      - TAR1090_RANGERINGSDISTANCES=50,100,150,200
      - TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
      #
      # --------------------------------------------------
      # GRAPHS1090 (Decoder and System Status Web Page) parameters:
      # The two 978 related parameters should only be included if you are running dump978 for UAT reception (USA only)
      - GRAPHS1090_DARKMODE=true
      - ENABLE_978=yes
      - URL_978=http://raspberrypi.localdomain:30980/skyaware978
      # 
      # --------------------------------------------------
      # Prometheus and InfluxDB connection parameters:
      - INFLUXDBV2_URL=${INFLUX_URL}
      - INFLUXDBV2_TOKEN=${INFLUX_TOKEN}
      - INFLUXDBV2_BUCKET=${INFLUX_BUCKET}
      - PROMETHEUS_ENABLE=false
    volumes:
      - /opt/adsb/ultrafeeder/globe_history:/var/globe_history
      - /opt/adsb/ultrafeeder/graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
      - /dev:/dev:ro
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M
